name: timescale-docs
channels:
  - conda-forge
dependencies:
  - docutils<0.18
  - fontconfig
  - freetype
  - graphviz
  - lxml
  - numpy
  - numpydoc
  - pip
  - python>=3.6
  - python-dateutil
  - setuptools_scm
  - sphinx
  - sphinx_rtd_theme
  - pip:
    - sphinx-argparse>=0.4
    - ..
